baseurl = "/"
languageCode = "en-us"
title = "Homepage"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "description", "date", "publishdate", "permalink"]

[outputs]
home = ["HTML", "RSS", "Algolia"]